config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do

  get "demo/slow"
  get "demo/fast"
  get 'demo/mail'
  root to: 'demo#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def slow
    render layout: 'slow'
  end

  def fast
    render layout: 'fast'
  end

  def index

  end

  def mail
    TestMailer.test().deliver
    render text: 'Mail Trying to send'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/views/demo/_a.html.haml
%legend Test (#{link_to 'Back', root_path})

app/views/demo/_b.html.haml
%div
  = render 'partial'

app/views/demo/_c.html.haml
%legend
  C Slow
- for i in 1..150 do
  - i = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
  %span{'data-temp'=>i.to_json}
    X

app/views/demo/_d.html.haml
%legend
  D Slow
- for i in 1..150 do
  - i = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
  %span{'data-temp'=>i.to_json}
    Y

app/views/demo/_partial.html.haml
%divhide{title: 'Form'}
  =simple_form_for :screen, url: '/dummy', remote: true, :html => {:class => 'form-horizontal dialogform','data-type' => :json} do |f|
    = f.input :name, as: :string, label: 'Name', required: false
    = f.input :alternative, as: :boolean, label: false, :inline_label => 'Boolean'
    = f.input :description, collection: ['A','B','C','D'], selected: 'A', label: 'Type', required: false
    - coll = [ %w{A SampleA}, %w{B SampleB}, %w{C SampleC}, %w{D SampleD}, %w{E SampleE}, %w{F SampleF}]
    = f.input :type, collection: coll, selected: 'A', label: 'Collection', required: false

app/views/demo/fast.html.haml
// Empty page since we are inlining it all to the template

app/views/demo/index.html.haml
Welcome to the Test

Here are the 2 pages to test with

= link_to('Fast',demo_fast_path)

= link_to('Slow',demo_slow_path)

=link_to('Mail',demo_mail_path)

app/views/demo/slow.html.haml
- object = {A:1,B:'test',C:{C1:'b',C2:Date.today}}
=content_for(:first) do
  %legend Test (#{link_to 'Back', root_path})
=content_for(:second) do
  %div
    = render 'partial'
=content_for(:third) do
  %legend
    C Slow
  - for i in 1..150 do
    - i = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
    %span{'data-temp'=>i.to_json}
      X
=content_for(:fourth) do
  %legend
    D Slow
  - for i in 1..150 do
    - i = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
    %span{'data-temp'=>i.to_json}
      Y
  = `ps -ef`

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails3BootstrapDeviseCancan</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/fast.html.haml
!!! 5
%html
  %head
    %meta{:charset => 'utf-8'}
    %meta{'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1'}
    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1.0'}
    %title= 'Aztec Learning System'
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
    = yield(:head)
  %body
    #main{role:'main'}
      .container-fluid.clear-top
        .row-fluid
          = render 'demo/a'
        .row-fluid
          = render 'demo/b'
        .row-fluid
          = render 'demo/c'
        .row-fluid
          = render 'demo/d'

app/views/layouts/slow.html.haml
!!! 5
%html
  %head
    %meta{:charset => 'utf-8'}
    %meta{'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1'}
    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1.0'}
    %title= 'Aztec Learning System'
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
    = yield(:head)
  %body
    #main{role:'main'}
      .container-fluid.clear-top
        .row-fluid
          = yield(:first)
        .row-fluid
          = yield(:second)
        .row-fluid
          = yield(:third)
        .row-fluid
          = yield(:fourth)